#!/usr/bin/env bash
set -euo pipefail

BASE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${ENV_FILE:-$BASE_DIR/.env}"
cd "$BASE_DIR"

MODE="run"
WIZARD="auto"

usage() {
  cat <<'USAGE'
Usage:
  scripts/run_prod.sh [--wizard] [--no-wizard] [--check] [--init-db-only]

Modes:
  --wizard       Run the first deployment setup wizard and write .env.
  --no-wizard    Do not prompt; fail if required settings are missing.
  --check        Validate environment and print the launch plan, then exit.
  --init-db-only Initialize or migrate the database, then exit.

Environment:
  ENV_FILE       Path to the env file. Default: .env in the repository root.

First deployment:
  Run scripts/run_prod.sh from a terminal. If .env is missing, the wizard asks
  for bootstrap passwords, runtime directories, bind address, HTTPS policy, and
  Gunicorn settings.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --wizard)
      WIZARD="yes"
      shift
      ;;
    --no-wizard)
      WIZARD="no"
      shift
      ;;
    --check)
      MODE="check"
      shift
      ;;
    --init-db-only)
      MODE="init-db-only"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

say() {
  printf '%s\n' "$*"
}

warn() {
  printf 'WARN: %s\n' "$*" >&2
}

die() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

is_interactive() {
  [[ -t 0 && -t 1 ]]
}

generate_secret() {
  python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(48))
PY
}

shell_quote() {
  python3 - "$1" <<'PY'
import shlex
import sys
print(shlex.quote(sys.argv[1]))
PY
}

prompt_default() {
  local label="$1"
  local default="$2"
  local value
  read -r -p "$label [$default]: " value
  printf '%s' "${value:-$default}"
}

prompt_yes_no() {
  local label="$1"
  local default="$2"
  local suffix="[y/N]"
  local value
  if [[ "$default" == "y" ]]; then
    suffix="[Y/n]"
  fi
  while true; do
    read -r -p "$label $suffix: " value
    value="${value:-$default}"
    case "${value,,}" in
      y|yes) return 0 ;;
      n|no) return 1 ;;
      *) say "請輸入 y 或 n。" ;;
    esac
  done
}

prompt_password() {
  local label="$1"
  local value confirm
  while true; do
    read -r -s -p "$label: " value
    printf '\n' >&2
    if [[ ${#value} -lt 12 ]]; then
      say "密碼至少建議 12 字元。" >&2
      continue
    fi
    read -r -s -p "再次輸入 $label: " confirm
    printf '\n' >&2
    if [[ "$value" != "$confirm" ]]; then
      say "兩次輸入不一致。" >&2
      continue
    fi
    printf '%s' "$value"
    return 0
  done
}

write_env_line() {
  local key="$1"
  local value="$2"
  printf '%s=%s\n' "$key" "$(shell_quote "$value")" >> "$ENV_FILE"
}

run_wizard() {
  is_interactive || die "缺少 $ENV_FILE，且目前不是互動終端。請先執行 scripts/run_prod.sh --wizard 或提供 ENV_FILE。"

  if [[ -e "$ENV_FILE" ]]; then
    if ! prompt_yes_no "$ENV_FILE 已存在，要覆寫嗎？" "n"; then
      say "保留既有 $ENV_FILE。"
      return 0
    fi
  fi

  say "Hackme Web 初次部署設定精靈"
  say "這會建立 $ENV_FILE；檔案權限會設為 600，請不要提交到 git。"
  say ""

  local runtime_root host port external_https force_https cookie_secure use_xff trusted_proxy_ips
  local workers timeout log_level create_manager create_test manager_password test_password
  local root_password storage_dir db_dir log_dir chat_dir anchor_dir reports_dir

  runtime_root="$(prompt_default "Runtime 資料根目錄" "$HOME/.local/share/hackme_web")"
  runtime_root="${runtime_root/#\~/$HOME}"
  db_dir="$runtime_root/database"
  log_dir="$runtime_root/logs"
  chat_dir="$runtime_root/chats"
  anchor_dir="$runtime_root/anchors"
  storage_dir="$runtime_root/storage"
  reports_dir="$runtime_root/reports"

  host="$(prompt_default "服務綁定 host" "0.0.0.0")"
  port="$(prompt_default "服務 port" "5000")"
  workers="$(prompt_default "Gunicorn workers" "4")"
  timeout="$(prompt_default "Gunicorn timeout 秒數" "60")"
  log_level="$(prompt_default "Gunicorn log level" "info")"

  if prompt_yes_no "服務會透過 HTTPS 對外提供嗎？例如反向代理或憑證終止在前端" "y"; then
    external_https="true"
  else
    external_https="false"
  fi
  force_https="$external_https"
  cookie_secure="$external_https"

  if prompt_yes_no "是否信任反向代理傳入的 X-Forwarded-For？" "n"; then
    use_xff="true"
    trusted_proxy_ips="$(prompt_default "可信任 proxy IP，多個用逗號" "127.0.0.1")"
  else
    use_xff="false"
    trusted_proxy_ips=""
  fi

  say ""
  say "設定 bootstrap 帳號。root 密碼只用於首次建立或預設密碼判定；首次登入後應立即變更。"
  root_password="$(prompt_password "root 初始密碼")"
  create_manager="false"
  create_test="false"
  manager_password=""
  test_password=""
  if prompt_yes_no "是否建立 manager/admin bootstrap 帳號？" "y"; then
    create_manager="true"
    manager_password="$(prompt_password "manager/admin 初始密碼")"
  fi
  if prompt_yes_no "是否建立測試帳號？正式上線通常不建議" "n"; then
    create_test="true"
    test_password="$(prompt_password "test 初始密碼")"
  fi

  mkdir -p "$(dirname "$ENV_FILE")"
  : > "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  {
    printf '# Hackme Web production env\n'
    printf '# Generated by scripts/run_prod.sh --wizard on %s\n\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  } >> "$ENV_FILE"

  write_env_line "FLASK_ENV" "production"
  write_env_line "APP_ENV" "production"
  write_env_line "IP_BLOCKING_ENABLED" "true"
  write_env_line "FORCE_HTTPS" "$force_https"
  write_env_line "SESSION_COOKIE_SECURE" "$cookie_secure"
  write_env_line "SESSION_COOKIE_HTTPONLY" "true"
  write_env_line "SESSION_COOKIE_SAMESITE" "Strict"
  write_env_line "USE_XFF" "$use_xff"
  write_env_line "TRUSTED_PROXY_IPS" "$trusted_proxy_ips"
  write_env_line "SESSION_SECRET" "$(generate_secret)"
  write_env_line "CSRF_SECRET_KEY" "$(generate_secret)"
  write_env_line "ROOT_INTEGRITY_SIGNING_KEY" "$(generate_secret)"
  write_env_line "TURNSTILE_SECRET_KEY" ""

  write_env_line "HTML_LEARNING_ROOT_PASSWORD" "$root_password"
  if [[ "$create_manager" == "true" ]]; then
    write_env_line "HTML_LEARNING_MANAGER_PASSWORD" "$manager_password"
  fi
  if [[ "$create_test" == "true" ]]; then
    write_env_line "HTML_LEARNING_TEST_PASSWORD" "$test_password"
  fi

  write_env_line "HTML_LEARNING_DB_DIR" "$db_dir"
  write_env_line "HTML_LEARNING_LOG_DIR" "$log_dir"
  write_env_line "HTML_LEARNING_CHAT_DIR" "$chat_dir"
  write_env_line "HTML_LEARNING_ANCHOR_DIR" "$anchor_dir"
  write_env_line "HTML_LEARNING_STORAGE_DIR" "$storage_dir"
  write_env_line "HTML_LEARNING_REPORTS_DIR" "$reports_dir"
  write_env_line "HTML_LEARNING_HOST" "$host"
  write_env_line "HTML_LEARNING_PORT" "$port"

  write_env_line "GUNICORN_BIND" "$host:$port"
  write_env_line "GUNICORN_WORKERS" "$workers"
  write_env_line "GUNICORN_TIMEOUT" "$timeout"
  write_env_line "GUNICORN_LOG_LEVEL" "$log_level"
  write_env_line "GUNICORN_ACCESS_LOG" "-"
  write_env_line "GUNICORN_ERROR_LOG" "-"

  mkdir -p "$db_dir" "$log_dir" "$chat_dir" "$anchor_dir" "$storage_dir" "$reports_dir"

  say ""
  say "已建立 $ENV_FILE"
  say "Runtime 目錄：$runtime_root"
  say "下一步會檢查環境並初始化資料庫。"
}

load_env_file() {
  if [[ -f "$ENV_FILE" ]]; then
    set -a
    # shellcheck disable=SC1090
    . "$ENV_FILE"
    set +a
  fi
}

should_run_wizard() {
  if [[ "$WIZARD" == "yes" ]]; then
    return 0
  fi
  if [[ "$WIZARD" == "no" ]]; then
    return 1
  fi
  [[ ! -f "$ENV_FILE" ]]
}

validate_port() {
  local value="$1"
  [[ "$value" =~ ^[0-9]+$ ]] || return 1
  (( value >= 1 && value <= 65535 ))
}

validate_environment() {
  local missing=0
  local port="${HTML_LEARNING_PORT:-5000}"
  local bind="${GUNICORN_BIND:-${HTML_LEARNING_HOST:-0.0.0.0}:$port}"
  local has_ffmpeg="false"
  local has_ffprobe="false"

  command -v python3 >/dev/null 2>&1 || { say "缺少 python3"; missing=1; }
  if ! command -v gunicorn >/dev/null 2>&1 && ! python3 -c "import gunicorn" >/dev/null 2>&1; then
    say "缺少 gunicorn，請先安裝：python3 -m pip install -r requirements.txt"
    missing=1
  fi
  [[ -n "${HTML_LEARNING_ROOT_PASSWORD:-}" ]] || { say "缺少 HTML_LEARNING_ROOT_PASSWORD。首次部署需要 root bootstrap 密碼。"; missing=1; }
  validate_port "$port" || { say "HTML_LEARNING_PORT 不是有效 port：$port"; missing=1; }

  for path_var in HTML_LEARNING_DB_DIR HTML_LEARNING_LOG_DIR HTML_LEARNING_CHAT_DIR HTML_LEARNING_ANCHOR_DIR HTML_LEARNING_STORAGE_DIR HTML_LEARNING_REPORTS_DIR; do
    local path="${!path_var:-}"
    if [[ -z "$path" ]]; then
      say "缺少 $path_var"
      missing=1
      continue
    fi
    if [[ "$path" != /* ]]; then
      say "$path_var 必須是絕對路徑：$path"
      missing=1
    fi
  done

  if [[ "$missing" == "1" ]]; then
    die "部署設定未完成。可執行 scripts/run_prod.sh --wizard 重新產生設定。"
  fi

  if command -v ffmpeg >/dev/null 2>&1; then
    has_ffmpeg="true"
  else
    warn "未找到 ffmpeg；影音平台的 HLS 衍生檔/轉檔功能將無法使用，影片仍可退回直接串流。"
  fi
  if command -v ffprobe >/dev/null 2>&1; then
    has_ffprobe="true"
  else
    warn "未找到 ffprobe；影音 metadata 偵測與 HLS 準備流程會失敗，請安裝 ffmpeg 套件。"
  fi
  if [[ -z "${CIVITAI_API_KEY:-}" ]]; then
    warn "未設定 CIVITAI_API_KEY；root 仍可使用本地模型上傳，但 Civitai 搜尋/下載不會啟用。"
  fi

  say "部署設定檢查"
  say "- env file: $ENV_FILE"
  say "- bind: $bind"
  say "- storage: ${HTML_LEARNING_STORAGE_DIR}"
  say "- database: ${HTML_LEARNING_DB_DIR}"
  say "- logs: ${HTML_LEARNING_LOG_DIR}"
  say "- HTTPS redirect: ${FORCE_HTTPS:-false}"
  say "- secure cookies: ${SESSION_COOKIE_SECURE:-false}"
  say "- HLS tooling: ffmpeg=${has_ffmpeg}, ffprobe=${has_ffprobe}"
  say "- Civitai search/download: $([[ -n "${CIVITAI_API_KEY:-}" ]] && printf 'configured' || printf 'disabled (missing CIVITAI_API_KEY)')"
  say "- root offline recovery: python3 scripts/root_recovery.py"
}

prepare_runtime_dirs() {
  mkdir -p \
    "${HTML_LEARNING_DB_DIR}" \
    "${HTML_LEARNING_LOG_DIR}" \
    "${HTML_LEARNING_CHAT_DIR}" \
    "${HTML_LEARNING_ANCHOR_DIR}" \
    "${HTML_LEARNING_STORAGE_DIR}" \
    "${HTML_LEARNING_REPORTS_DIR}"
}

init_database() {
  python3 - <<'PY'
import server

server.init_db(
    ensure_secure_audit_columns=server.ensure_secure_audit_columns,
    ensure_user_columns=server.ensure_user_columns,
    ensure_appeal_columns=server.ensure_appeal_columns,
    ensure_session_columns=server.ensure_session_columns,
    ensure_security_support_schema=server.ensure_security_support_schema,
    ensure_points_economy_schema=server.ensure_points_economy_schema,
    ensure_official_chat_room=server.ensure_official_chat_room,
    hash_password=server.hash_password,
)
conn = server.get_db()
try:
    server.ensure_trading_schema(conn)
    conn.commit()
finally:
    conn.close()
print("database ready")
PY
}

if should_run_wizard; then
  run_wizard
fi

load_env_file

export IP_BLOCKING_ENABLED="${IP_BLOCKING_ENABLED:-true}"
export FORCE_HTTPS="${FORCE_HTTPS:-true}"
export SESSION_COOKIE_SECURE="${SESSION_COOKIE_SECURE:-true}"
export SESSION_COOKIE_HTTPONLY="${SESSION_COOKIE_HTTPONLY:-true}"
export SESSION_COOKIE_SAMESITE="${SESSION_COOKIE_SAMESITE:-Strict}"
export GUNICORN_BIND="${GUNICORN_BIND:-${HTML_LEARNING_HOST:-0.0.0.0}:${HTML_LEARNING_PORT:-5000}}"
export GUNICORN_WORKERS="${GUNICORN_WORKERS:-4}"
export GUNICORN_TIMEOUT="${GUNICORN_TIMEOUT:-60}"
export GUNICORN_LOG_LEVEL="${GUNICORN_LOG_LEVEL:-info}"
export GUNICORN_ACCESS_LOG="${GUNICORN_ACCESS_LOG:--}"
export GUNICORN_ERROR_LOG="${GUNICORN_ERROR_LOG:--}"

validate_environment
prepare_runtime_dirs

if [[ "$MODE" == "check" ]]; then
  say "check complete"
  exit 0
fi

init_database

if [[ "$MODE" == "init-db-only" ]]; then
  exit 0
fi

say "Starting Hackme Web with Gunicorn..."
exec python3 -m gunicorn \
  --bind "$GUNICORN_BIND" \
  --workers "$GUNICORN_WORKERS" \
  --timeout "$GUNICORN_TIMEOUT" \
  --access-logfile "$GUNICORN_ACCESS_LOG" \
  --error-logfile "$GUNICORN_ERROR_LOG" \
  --capture-output \
  --log-level "$GUNICORN_LOG_LEVEL" \
  server:app
